### ISSUE TITLE
Tick mark for logo. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/SpekCheck#64]
I can't find the exact font a grabbed it from, Lothar sent it to me as it is the same one as from SIMcheck. I think it is identical to the one in windings2, character 80 on my mac.

**Comment by iandobbie** [comment]
However wingdings is not free so we should try find an equivalent.

**Comment by carandraug** [comment]
There is now a svg file with the intersection of the character converted to shape and a single row image of the visible spectrum. The python code to generate the visible spectrum is also on the repository. Because the final png is pretty small, I am also adding to the repository.

The web interface uses that png instead of trying to draw it.
