### ISSUE TITLE
lumencor excitation spectra

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/SpekCheck#76]
Instead of the multiple lumencor-* excitation sources, shouldn't we have a single spectra for the lumencor excitation source and have their corresponding filters on the excitation path?

**Comment by iandobbie** [comment]
No because it is separate led’s which can be individually turned on.

Ian

Sent from my iPhone

On 18 May 2018, at 17:39, Carnë Draug <notifications@github.com<mailto:notifications@github.com>> wrote:


Instead of the multiple lumencor-* excitation sources, shouldn't we have a single spectra for the lumencor excitation source and have their corresponding filters on the excitation path?

**Comment by carandraug** [comment]
> No because it is separate led’s which can be individually turned on.

Ok. I thought all of the leds were on, which is why SEMrock only has one spectrum for lumencor, and that was a filter on the excitation path that would filter individual leds.

Closing this issue then.
